name: Test Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Usa una versione moderna di Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with pytest
      env:
        # Forniamo una chiave FINTA. I test non la useranno (perché
        # usiamo il mock), ma il client AI ne ha bisogno per inizializzarsi.
        OPENAI_API_KEY: "dummy-key-for-testing"
      run: |
        pytest